name: Build Push Deploy

on:
  push:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Verify Repository
        run: |
          pwd
          ls -la

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      

      - name: Build React Application
        run: npm run build

      # Uncomment if your project has tests
      # - name: Run Tests
      #   run: npm test -- --watchAll=false

  docker:
    needs: build-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/myimage:${{ github.run_number }} .

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/myimage:${{ github.run_number }}

  security:
    needs: docker
    runs-on: ubuntu-latest

    steps:
      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@0.36.0
        with:
          scan-type: image
          scan-ref: ${{ secrets.DOCKER_USERNAME }}/myimage:${{ github.run_number }}
          format: table
          exit-code: "1"
          severity: CRITICAL,HIGH

  deploy:
    needs: security
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/react-app \
          react-app=${{ secrets.DOCKER_USERNAME }}/myimage:${{ github.run_number }}

      - name: Wait for Rollout
        run: |
          kubectl rollout status deployment/react-app

      - name: Verify Pods
        run: |
          kubectl get pods

      - name: Verify Services
        run: |
          kubectl get svc
